package unlikely.alice.ninepm.ui.theme

import androidx.compose.ui.graphics.Color

object Colors {
    val LightPrimary = Color(0xFF6650A4)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightPrimaryContainer = Color(0xFFE8DDFF)
    val LightOnPrimaryContainer = Color(0xFF21005D)
    val LightSecondary = Color(0xFF615B71)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightSecondaryContainer = Color(0xFFE8DEF8)
    val LightOnSecondaryContainer = Color(0xFF1D192B)
    val LightTertiary = Color(0xFF7D5260)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightTertiaryContainer = Color(0xFFFFD9E3)
    val LightOnTertiaryContainer = Color(0xFF31101D)
    val LightError = Color(0xFFBA1A1A)
    val LightErrorContainer = Color(0xFFFFDAD6)
    val LightOnError = Color(0xFFFFFFFF)
    val LightOnErrorContainer = Color(0xFF410002)
    val LightBackground = Color(0xFFFFFBFF)
    val LightOnBackground = Color(0xFF1C1B1E)
    val LightSurface = Color(0xFFFFFBFF)
    val LightOnSurface = Color(0xFF1C1B1E)
    val LightSurfaceVariant = Color(0xFFE6E0EC)
    val LightOnSurfaceVariant = Color(0xFF49454E)
    val LightOutline = Color(0xFF7A757F)
    val LightInverseOnSurface = Color(0xFFF4EFF4)
    val LightInverseSurface = Color(0xFF313033)
    val LightInversePrimary = Color(0xFFCFBDFF)
    val LightSurfaceTint = Color(0xFF6650A4)

    val DarkPrimary = Color(0xFFCFBDFF)
    val DarkOnPrimary = Color(0xFF371E73)
    val DarkPrimaryContainer = Color(0xFF4E378B)
    val DarkOnPrimaryContainer = Color(0xFFE8DDFF)
    val DarkSecondary = Color(0xFFCBC3DC)
    val DarkOnSecondary = Color(0xFF332D41)
    val DarkSecondaryContainer = Color(0xFF494458)
    val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
    val DarkTertiary = Color(0xFFEFB8C8)
    val DarkOnTertiary = Color(0xFF492532)
    val DarkTertiaryContainer = Color(0xFF633B49)
    val DarkOnTertiaryContainer = Color(0xFFFFD9E3)
    val DarkError = Color(0xFFFFB4AB)
    val DarkErrorContainer = Color(0xFF93000A)
    val DarkOnError = Color(0xFF690005)
    val DarkOnErrorContainer = Color(0xFFFFDAD6)
    val DarkBackground = Color(0xFF1C1B1E)
    val DarkOnBackground = Color(0xFFE6E1E6)
    val DarkSurface = Color(0xFF1C1B1E)
    val DarkOnSurface = Color(0xFFE6E1E6)
    val DarkSurfaceVariant = Color(0xFF49454E)
    val DarkOnSurfaceVariant = Color(0xFFCAC4CF)
    val DarkOutline = Color(0xFF948F99)
    val DarkInverseOnSurface = Color(0xFF1C1B1E)
    val DarkInverseSurface = Color(0xFFE6E1E6)
    val DarkInversePrimary = Color(0xFF6650A4)
    val DarkSurfaceTint = Color(0xFFCFBDFF)

    val Bluetooth = Color(0xFF0082FC)
}

